### ISSUE TITLE
The issue with the expert scoring system;

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#4]
- Perhaps most importantly, I was not convinced by the expert analysis (p. 15/16). “All players with a score higher than 10 are considered experts (n = 135).” Isn't it likely that a sizeable number of these experts just happened to guess correctly? The scoring system is not entirely clear from the paper, but given the large number of participants, a many “experts” could just have been lucky. My suggestion would be to remove this part of the analysis, or consider setting-up a "real" expert analysis.

**Comment by emanjavacas** [comment]
I feel it's a valid point. However, they might be missing the fact of the sudden death. Which makes going past the 10th question quite an anomaly. I am now unsure if for the experts we only used their responses past the 10th Q or all of them. If the former, then I think we can just point that out?
Perhaps we could define experts based on some kind of percentiles in terms of correct answers instead...?

**Comment by fbkarsdorp** [comment]
Yes, it's a valid point. I guess it has to do with the way we frame it. The reviewer is right in saying that we can't be sure participants with a score > 10 are actually experts. All we can say is that their score is significantly better than that of the others. We could select all participants with a score 1 std away from the mean and analyze those. I still think it's informative to zoom in on the group of people showing better performance.

**Comment by fbkarsdorp** [comment]
OK. I made some changes. The way I've tried to solve it is by (i) merging it with the subjective feature analysis, and (ii) reframing the analysis as a way to zoom in on the high-scoring participants. That way we don't have to use labels like 'experts', because, indeed, we cannot state that they are actually experts. What we do know is that they performed better than the others, which is reason enough to have a closer look. I re-did the analysis zooming in on participants with a score > 1 standard deviation from the mean. That amounts to 72 participants (which is about half of the previous set with > 10). Results are pretty much the same, even a bit more pronounced.
