### ISSUE TITLE
The issue withe training corpus

### ISSUE THREAD

**Issue by emanjavacas** [fbkarsdorp/deepflow-analysis#6]
- About the training materials: can you say a little about how the OHHLA corpus was collected and whether there is any quality control of the lyrics? Why didn't you use rap.genius? It would also be good, in this context, to refer to Bradley & DuBois' (2010) Anthology of Rap, Yale University Press, since it is the first ‘serious’ anthology of rap lyrics. At the time, this anthology got quite a bit of criticism about the quality of the transliterations, which are indeed notoriously difficult for rap lyrics. How does the possible noisiness of the data influence the models?

**Comment by emanjavacas** [comment]
- I am not aware of any quality control. Have we done such a thing? 
- Genius doesn't allow to download lyrics.
- The Anthology is probably too short anyway.

**Comment by fbkarsdorp** [comment]
1. No, we didn't do quality control. I only had the impression that the quality was quite good (but that's not something to put into the paper ;)) 
2. Indeed, and the database is smaller;
3. True.

**Comment by fbkarsdorp** [comment]
I added the following footnote:

While other online rap platforms exist (e.g.\ Genius), we chose OHHLA as it allows more efficient scraping, and shares many transcriptions with more well-known platforms. The downside of using lyrics from these online platforms is that it cannot be demonstrated to what extent quality control measures have been applied. However, since OHHLA (like Genius) is a community effort, with many active contributors commenting on and correcting rap transcriptions, we can be confident
that the quality of the rap lyrics is good enough for our purposes.
